# Generated by Django 4.2.7 on 2023-11-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('salada', 'Comida Salada'), ('dulce', 'Comida Dulce')], default='salada', max_length=100),
        ),
    ]
