# Generated by Django 4.2.7 on 2023-11-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_receta_imagen_receta_subtitulo_alter_receta_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(default='images/receta_default.jpg', upload_to='images'),
        ),
    ]
