# Generated by Django 4.2.7 on 2023-11-23 22:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_remove_comentario_creador_alter_comentario_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='instrucciones',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
